management:
  endpoints:
    web:
      exposure:
        include: "*" # Expose all endpoints
  endpoint:
    health:
      show-details: "always" # Always show health details
      show-components: "always" # Show health components
    httptrace:
      enabled: true # Enable HTTP trace endpoint